name: ci

# 在 push 和 PR 时运行
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build: # 注意：列表里会显示成 “ci / build”
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build
